import { PROJECT_STATUS, PAYMENT_STATUS } from './constants';
import { generateId } from './helpers';

// Mock project data
export const mockProjects = [
  {
    id: generateId(),
    name: 'E-commerce Website Redesign',
    description: 'Complete redesign of the company e-commerce platform with modern UI/UX',
    status: PROJECT_STATUS.ACTIVE,
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-04-15'),
    budget: 45000,
    totalPaid: 22500,
    clientName: 'TechCorp Solutions',
    teamMembers: ['john.doe@example.com', 'jane.smith@example.com'],
    tags: ['web', 'ecommerce', 'react'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: generateId(),
    name: 'Mobile App Development',
    description: 'Native iOS and Android app for customer engagement and loyalty program',
    status: PROJECT_STATUS.ACTIVE,
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-06-01'),
    budget: 75000,
    totalPaid: 30000,
    clientName: 'RetailMax Inc',
    teamMembers: ['alice.johnson@example.com', 'bob.wilson@example.com'],
    tags: ['mobile', 'ios', 'android'],
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-02-18'),
  },
  {
    id: generateId(),
    name: 'Data Analytics Dashboard',
    description: 'Business intelligence dashboard with real-time analytics and reporting',
    status: PROJECT_STATUS.COMPLETED,
    startDate: new Date('2023-10-01'),
    endDate: new Date('2024-01-31'),
    budget: 32000,
    totalPaid: 32000,
    clientName: 'DataDriven LLC',
    teamMembers: ['charlie.brown@example.com'],
    tags: ['analytics', 'dashboard', 'bi'],
    createdAt: new Date('2023-09-20'),
    updatedAt: new Date('2024-01-31'),
  },
  {
    id: generateId(),
    name: 'Cloud Migration Project',
    description: 'Migration of legacy systems to AWS cloud infrastructure',
    status: PROJECT_STATUS.ON_HOLD,
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-05-01'),
    budget: 85000,
    totalPaid: 17000,
    clientName: 'Enterprise Systems Co',
    teamMembers: ['david.lee@example.com', 'emma.davis@example.com'],
    tags: ['cloud', 'aws', 'migration'],
    createdAt: new Date('2023-12-15'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: generateId(),
    name: 'Marketing Website',
    description: 'Modern marketing website with CMS integration and SEO optimization',
    status: PROJECT_STATUS.COMPLETED,
    startDate: new Date('2023-11-01'),
    endDate: new Date('2024-01-15'),
    budget: 18000,
    totalPaid: 18000,
    clientName: 'StartupXYZ',
    teamMembers: ['frank.miller@example.com'],
    tags: ['website', 'cms', 'seo'],
    createdAt: new Date('2023-10-20'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: generateId(),
    name: 'API Integration Platform',
    description: 'Microservices architecture with REST API and third-party integrations',
    status: PROJECT_STATUS.CANCELLED,
    startDate: new Date('2023-12-01'),
    endDate: new Date('2024-03-01'),
    budget: 55000,
    totalPaid: 11000,
    clientName: 'IntegrationHub',
    teamMembers: ['grace.taylor@example.com', 'henry.clark@example.com'],
    tags: ['api', 'microservices', 'integration'],
    createdAt: new Date('2023-11-25'),
    updatedAt: new Date('2024-01-20'),
  },
];

// Mock payment data
export const mockPayments = [
  {
    id: generateId(),
    projectId: mockProjects[0].id,
    amount: 15000,
    currency: 'INR',
    status: PAYMENT_STATUS.COMPLETED,
    paymentDate: new Date('2024-01-20'),
    description: 'Initial project milestone payment',
    proofFiles: [],
    paymentMethod: 'Bank Transfer',
    transactionId: 'TXN-001-2024',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: generateId(),
    projectId: mockProjects[0].id,
    amount: 7500,
    currency: 'INR',
    status: PAYMENT_STATUS.COMPLETED,
    paymentDate: new Date('2024-02-15'),
    description: 'Second milestone payment',
    proofFiles: [],
    paymentMethod: 'Credit Card',
    transactionId: 'TXN-002-2024',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: generateId(),
    projectId: mockProjects[1].id,
    amount: 25000,
    currency: 'INR',
    status: PAYMENT_STATUS.COMPLETED,
    paymentDate: new Date('2024-02-05'),
    description: 'Project kickoff payment',
    proofFiles: [],
    paymentMethod: 'Wire Transfer',
    transactionId: 'TXN-003-2024',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: generateId(),
    projectId: mockProjects[1].id,
    amount: 5000,
    currency: 'INR',
    status: PAYMENT_STATUS.PENDING,
    paymentDate: new Date('2024-03-01'),
    description: 'Monthly progress payment',
    proofFiles: [],
    paymentMethod: 'Bank Transfer',
    transactionId: null,
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-02-25'),
  },
];

// Mock user data
export const mockUsers = [
  {
    id: generateId(),
    email: 'admin@projecttracker.com',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
    avatar: null,
    permissions: ['read', 'write', 'delete', 'admin'],
    createdAt: new Date('2023-01-01'),
    lastLoginAt: new Date('2024-02-20'),
  },
  {
    id: generateId(),
    email: 'manager@projecttracker.com',
    firstName: 'Project',
    lastName: 'Manager',
    role: 'manager',
    avatar: null,
    permissions: ['read', 'write'],
    createdAt: new Date('2023-06-15'),
    lastLoginAt: new Date('2024-02-19'),
  },
  {
    id: generateId(),
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    role: 'member',
    avatar: null,
    permissions: ['read'],
    createdAt: new Date('2023-08-10'),
    lastLoginAt: new Date('2024-02-18'),
  },
  {
    id: generateId(),
    email: 'jane.smith@example.com',
    firstName: 'Jane',
    lastName: 'Smith',
    role: 'member',
    avatar: null,
    permissions: ['read'],
    createdAt: new Date('2023-09-05'),
    lastLoginAt: new Date('2024-02-17'),
  },
  {
    id: generateId(),
    email: 'alice.johnson@example.com',
    firstName: 'Alice',
    lastName: 'Johnson',
    role: 'manager',
    avatar: null,
    permissions: ['read', 'write'],
    createdAt: new Date('2023-10-20'),
    lastLoginAt: new Date('2024-02-16'),
  },
];

// Helper function to get project by ID
export const getProjectById = (id) => {
  return mockProjects.find(project => project.id === id);
};

// Helper function to get payments by project ID
export const getPaymentsByProjectId = (projectId) => {
  return mockPayments.filter(payment => payment.projectId === projectId);
};

// Helper function to get all payments for a user's projects
export const getAllPayments = () => {
  return mockPayments;
};